<?php

$geo_array = array(
array(1, 'Австралия', 'Australia', 'AU'),
array(2, 'Малайзия', 'Malaysia', 'MY'),
array(3, 'Республика Корея', 'Korea', 'KR'),
array(4, 'Китай', 'China', 'CN'),
array(5, 'Япония', 'Japan', 'JP'),
array(6, 'Индия', 'India', 'IN'),
array(7, 'Тайвань', 'Taiwan', 'TW'),
array(8, 'Гонконг', 'Hong Kong', 'HK'),
array(9, 'Таиланд', 'Thailand', 'TH'),
array(11, 'Вьетнам', 'Vietnam', 'VN'),
array(12, 'Франция', 'France', 'FR'),
array(13, 'Италия', 'Italy', 'IT'),
array(14, 'Объединенные Арабские Эмираты', 'United Arab Emirates', 'AE'),
array(15, 'Швеция', 'Sweden', 'SE'),
array(16, 'Казахстан', 'Kazakhstan', 'KZ'),
array(17, 'Португалия', 'Portugal', 'PT'),
array(18, 'Греция', 'Greece', 'GR'),
array(19, 'Саудовская Аравия', 'Saudi Arabia', 'SA'),
array(20, 'Российская Федерация', 'Russian Federation', 'RU'),
array(21, 'Великобритания', 'United Kingdom', 'GB'),
array(22, 'Дания', 'Denmark', 'DK'),
array(23, 'США', 'United States', 'US'),
array(24, 'Канада', 'Canada', 'CA'),
array(25, 'Мексика', 'Mexico', 'MX'),
array(26, 'Бермуды', 'Bermuda', 'BM'),
array(27, 'Пуэрто Рико', 'Puerto Rico', 'PR'),
array(28, 'Виргинские Острова США', 'Virgin Islands, U.S.', 'VI'),
array(29, 'Германия', 'Germany', 'DE'),
array(30, 'Иран', 'Iran', 'IR'),
array(31, 'Боливия', 'Bolivia', 'BO'),
array(32, 'Монтсеррат', 'Montserrat', 'MS'),
array(33, 'Нидерланды', 'Netherlands', 'NL'),
array(34, 'Израиль', 'Israel', 'IL'),
array(35, 'Испания', 'Spain', 'ES'),
array(36, 'Багамские острова', 'Bahamas', 'BS'),
array(37, 'Сент-Винсент и Гренадины', 'Saint Vincent and the Grenadines', 'VC'),
array(38, 'Чили', 'Chile', 'CL'),
array(39, 'Новая Каледония', 'New Caledonia', 'NC'),
array(40, 'Аргентина', 'Argentina', 'AR'),
array(41, 'Доминика', 'Dominica', 'DM'),
array(42, 'Сингапур', 'Singapore', 'SG'),
array(43, 'Непал', 'Nepal', 'NP'),
array(44, 'Филиппины', 'Philippines', 'PH'),
array(45, 'Индонезия', 'Indonesia', 'ID'),
array(46, 'Пакистан', 'Pakistan', 'PK'),
array(47, 'Токелау', 'Tokelau', 'TK'),
array(48, 'Новая Зеландия', 'New Zealand', 'NZ'),
array(49, 'Камбоджа', 'Cambodia', 'KH'),
array(50, 'Макау', 'Macau', 'MO'),
array(51, 'Папуа Новая Гвинея', 'Papua New Guinea', 'PG'),
array(52, 'Мальдивские острова', 'Maldives', 'MV'),
array(53, 'Афганистан', 'Afghanistan', 'AF'),
array(54, 'Бангладеш', 'Bangladesh', 'BD'),
array(55, 'Ирландия', 'Ireland', 'IE'),
array(56, 'Бельгия', 'Belgium', 'BE'),
array(57, 'Белиз', 'Belize', 'BZ'),
array(58, 'Бразилия', 'Brazil', 'BR'),
array(59, 'Швейцария', 'Switzerland', 'CH'),
array(60, 'Южно-Африканская Республика', 'South Africa', 'ZA'),
array(61, 'Египет', 'Egypt', 'EG'),
array(62, 'Нигерия', 'Nigeria', 'NG'),
array(63, 'Танзания', 'Tanzania', 'TZ'),
array(64, 'Замбия', 'Zambia', 'ZM'),
array(65, 'Сенегал', 'Senegal', 'SN'),
array(66, 'Гана', 'Ghana', 'GH'),
array(67, 'Судан', 'Sudan', 'SD'),
array(68, 'Камерун', 'Cameroon', 'CM'),
array(69, 'Малави', 'Malawi', 'MW'),
array(70, 'Ангола', 'Angola', 'AO'),
array(71, 'Кения', 'Kenya', 'KE'),
array(72, 'Габон', 'Gabon', 'GA'),
array(73, 'Мали', 'Mali', 'ML'),
array(74, 'Бенин', 'Benin', 'BJ'),
array(75, 'Мадагаскар', 'Madagascar', 'MG'),
array(76, 'Чад', 'Chad', 'TD'),
array(77, 'Ботсвана', 'Botswana', 'BW'),
array(78, 'Ливия', 'Libya', 'LY'),
array(79, 'Кабо-Верде', 'Cape Verde', 'CV'),
array(80, 'Руанда', 'Rwanda', 'RW'),
array(81, 'Мозамбик', 'Mozambique', 'MZ'),
array(82, 'Гамбия', 'Gambia', 'GM'),
array(83, 'Лесото', 'Lesotho', 'LS'),
array(84, 'Маврикий', 'Mauritius', 'MU'),
array(85, 'Конго', 'Congo', 'CG'),
array(86, 'Уганда', 'Uganda', 'UG'),
array(87, 'Буркина Фасо', 'Burkina Faso', 'BF'),
array(88, 'Сьерра-Леоне', 'Sierra Leone', 'SL'),
array(89, 'Сомали', 'Somalia', 'SO'),
array(90, 'Зимбабве', 'Zimbabwe', 'ZW'),
array(91, 'Демократическая Республика Конго', 'Democratic Republic Of The Congo', 'CD'),
array(92, 'Нигер', 'Niger', 'NE'),
array(93, 'Центрально-Африканская Республика', 'Central African Republic', 'CF'),
array(94, 'Свазиленд', 'Swaziland', 'SZ'),
array(95, 'Того', 'Togo', 'TG'),
array(96, 'Гвинея', 'Guinea', 'GN'),
array(97, 'Либерия', 'Liberia', 'LR'),
array(98, 'Сейшеллы', 'Seychelles', 'SC'),
array(99, 'Марокко', 'Morocco', 'MA'),
array(100, 'Алжир', 'Algeria', 'DZ'),
array(101, 'Мавритания', 'Mauritania', 'MR'),
array(102, 'Намибия', 'Namibia', 'NA'),
array(103, 'Джибути', 'Djibouti', 'DJ'),
array(105, 'Коморские острова', 'Comoros', 'KM'),
array(106, 'Реюньон', 'Reunion', 'RE'),
array(107, 'Экваториальная Гвинея', 'Equatorial Guinea', 'GQ'),
array(108, 'Тунис', 'Tunisia', 'TN'),
array(109, 'Турция', 'Turkey', 'TR'),
array(110, 'Польша', 'Poland', 'PL'),
array(111, 'Латвия', 'Latvia', 'LV'),
array(112, 'Украина', 'Ukraine', 'UA'),
array(113, 'Беларусь', 'Belarus', 'BY'),
array(114, 'Чехия', 'Czech Republic', 'CZ'),
array(115, 'Палестина', 'Palestinian Territory', 'PS'),
array(116, 'Исландия', 'Iceland', 'IS'),
array(117, 'Кипр', 'Cyprus', 'CY'),
array(118, 'Венгрия', 'Hungary', 'HU'),
array(119, 'Словакия', 'Slovakia', 'SK'),
array(120, 'Сербия', 'Serbia', 'RS'),
array(121, 'Болгария', 'Bulgaria', 'BG'),
array(122, 'Оман', 'Oman', 'OM'),
array(123, 'Румыния', 'Romania', 'RO'),
array(124, 'Грузия', 'Georgia', 'GE'),
array(125, 'Норвегия', 'Norway', 'NO'),
array(126, 'Армения', 'Armenia', 'AM'),
array(127, 'Австрия', 'Austria', 'AT'),
array(128, 'Албания', 'Albania', 'AL'),
array(129, 'Словения', 'Slovenia', 'SI'),
array(130, 'Панама', 'Panama', 'PA'),
array(131, 'Бруней', 'Brunei Darussalam', 'BN'),
array(132, 'Шри-Ланка', 'Sri Lanka', 'LK'),
array(133, 'Черногория', 'Montenegro', 'ME'),
array(134, 'Европейский Союз', 'Europe', 'EU'),
array(135, 'Таджикистан', 'Tajikistan', 'TJ'),
array(136, 'Ирак', 'Iraq', 'IQ'),
array(137, 'Ливан', 'Lebanon', 'LB'),
array(138, 'Молдова', 'Moldova', 'MD'),
array(139, 'Финляндия', 'Finland', 'FI'),
array(140, 'Эстония', 'Estonia', 'EE'),
array(141, 'Босния и Герцеговина', 'Bosnia and Herzegovina', 'BA'),
array(142, 'Кувейт', 'Kuwait', 'KW'),
array(143, 'Аландские острова', 'Aland Islands', 'AX'),
array(144, 'Литва', 'Lithuania', 'LT'),
array(145, 'Люксембург', 'Luxembourg', 'LU'),
array(146, 'Антигуа и Барбуда', 'Antigua and Barbuda', 'AG'),
array(147, 'Македония', 'Macedonia', 'MK'),
array(148, 'Сан-Марино', 'San Marino', 'SM'),
array(149, 'Мальта', 'Malta', 'MT'),
array(150, 'Фолклендские острова', 'Falkland Islands', 'FK'),
array(151, 'Бахрейн', 'Bahrain', 'BH'),
array(152, 'Узбекистан', 'Uzbekistan', 'UZ'),
array(153, 'Азербайджан', 'Azerbaijan', 'AZ'),
array(154, 'Монако', 'Monaco', 'MC'),
array(155, 'Гаити', 'Haiti', 'HT'),
array(156, 'Гуам', 'Guam', 'GU'),
array(157, 'Ямайка', 'Jamaica', 'JM'),
array(158, 'Внешние малые острова США', 'United States Minor Outlying Islands', 'UM'),
array(159, 'Микронезия', 'Micronesia', 'FM'),
array(160, 'Эквадор', 'Ecuador', 'EC'),
array(161, 'Перу', 'Peru', 'PE'),
array(162, 'Каймановы острова', 'Cayman Islands', 'KY'),
array(163, 'Колумбия', 'Colombia', 'CO'),
array(164, 'Гондурас', 'Honduras', 'HN'),
array(165, 'Антильские острова', 'Netherlands Antilles', 'AN'),
array(166, 'Йемен', 'Yemen', 'YE'),
array(167, 'Британские Виргинские острова', 'Virgin Islands, British', 'VG'),
array(168, 'Сирия', 'Syria', 'SY'),
array(169, 'Никарагуа', 'Nicaragua', 'NI'),
array(170, 'Доминиканская республика', 'Dominican Republic', 'DO'),
array(171, 'Гренада', 'Grenada', 'GD'),
array(172, 'Гватемала', 'Guatemala', 'GT'),
array(173, 'Коста-Рика', 'Costa Rica', 'CR'),
array(174, 'Сальвадор', 'El Salvador', 'SV'),
array(175, 'Венесуэла', 'Venezuela', 'VE'),
array(176, 'Барбадос', 'Barbados', 'BB'),
array(177, 'Тринидад и Тобаго', 'Trinidad and Tobago', 'TT'),
array(178, 'Буве', 'Bouvet Island', 'BV'),
array(179, 'Маршалловы острова', 'Marshall Islands', 'MH'),
array(180, 'Острова Кука', 'Cook Islands', 'CK'),
array(181, 'Гибралтар', 'Gibraltar', 'GI'),
array(182, 'Парагвай', 'Paraguay', 'PY'),
array(247, 'Южный Судан', 'South Sudan', 'SS'),
array(184, 'Самоа', 'Samoa', 'WS'),
array(185, 'Сент Китс и Невис', 'Saint Kitts and Nevis', 'KN'),
array(186, 'Фиджи', 'Fiji', 'FJ'),
array(187, 'Уругвай', 'Uruguay', 'UY'),
array(188, 'Северные Марианские острова', 'Northern Mariana Islands', 'MP'),
array(189, 'Палау', 'Palau', 'PW'),
array(190, 'Катар', 'Qatar', 'QA'),
array(191, 'Иордания', 'Jordan', 'JO'),
array(192, 'Американское Самоа', 'American Samoa', 'AS'),
array(193, 'Туркс и Кейкос', 'Turks and Caicos Islands', 'TC'),
array(194, 'Святая Люсия', 'Saint Lucia', 'LC'),
array(195, 'Монголия', 'Mongolia', 'MN'),
array(196, 'Ватикан', 'Holy See', 'VA'),
array(197, 'Арулько', 'Aruba', 'AW'),
array(198, 'Гайана', 'Guyana', 'GY'),
array(199, 'Суринам', 'Suriname', 'SR'),
array(200, 'Остров Мэн', 'Isle of Man', 'IM'),
array(201, 'Вануату', 'Vanuatu', 'VU'),
array(202, 'Хорватия', 'Croatia', 'HR'),
array(203, 'Ангуилья', 'Anguilla', 'AI'),
array(204, 'Сен-Пьер и Микелон', 'Saint Pierre and Miquelon', 'PM'),
array(205, 'Гваделупа', 'Guadeloupe', 'GP'),
array(206, 'Сен-Мартен', 'Saint Martin', 'MF'),
array(207, 'Гернси', 'Guernsey', 'GG'),
array(208, 'Бурунди', 'Burundi', 'BI'),
array(209, 'Туркменистан', 'Turkmenistan', 'TM'),
array(210, 'Кыргызстан', 'Kyrgyzstan', 'KG'),
array(211, 'Мьянма', 'Myanmar', 'MM'),
array(212, 'Бутан', 'Bhutan', 'BT'),
array(213, 'Лихтенштейн', 'Liechtenstein', 'LI'),
array(214, 'Фарерские острова', 'Faroe Islands', 'FO'),
array(215, 'Эфиопия', 'Ethiopia', 'ET'),
array(216, 'Мартиника', 'Martinique', 'MQ'),
array(217, 'Джерси', 'Jersey', 'JE'),
array(218, 'Андорра', 'Andorra', 'AD'),
array(219, 'Антарктида', 'Antarctica', 'AQ'),
array(220, 'Британская территория в Индийском океане', 'British Indian Ocean Territory', 'IO'),
array(221, 'Гренландия', 'Greenland', 'GL'),
array(222, 'Гвинея-Бисау', 'Guinea-Bissau', 'GW'),
array(223, 'Эритрея', 'Eritrea', 'ER'),
array(224, 'Уоллис и Футуна', 'Wallis and Futuna', 'WF'),
array(225, 'Французская Полинезия', 'French Polynesia', 'PF'),
array(226, 'Куба', 'Cuba', 'CU'),
array(227, 'Тонга', 'Tonga', 'TO'),
array(228, 'Восточный Тимор', 'Timor-Leste', 'TL'),
array(229, 'Сан-Томе и Принсипи', 'Sao Tome and Principe', 'ST'),
array(230, 'Французская Гвинея', 'French Guiana', 'GF'),
array(231, 'Соломоновы острова', 'Solomon Islands', 'SB'),
array(232, 'Тувалу', 'Tuvalu', 'TV'),
array(233, 'Кирибати', 'Kiribati', 'KI'),
array(234, 'Ниуэ', 'Niue', 'NU'),
array(235, 'Норфолк', 'Norfolk Island', 'NF'),
array(236, 'Науру', 'Nauru', 'NR'),
array(237, 'Майотта', 'Mayotte', 'YT'),
array(238, 'Питкэрн', 'Pitcairn Islands', 'PN'),
array(239, 'Кот-д Ивуар', 'Cote D Ivoire', 'CI'),
array(240, 'Лаос', 'Lao', 'LA'),
array(241, 'Корейская Народно-Демократическая Республика', 'Democratic People s Republic of Korea', 'KP'),
array(242, 'Свальбард и Ян-Майен', 'Svalbard and Jan Mayen', 'SJ'),
array(243, 'Остров Святой Елены', 'Saint Helena', 'SH'),
array(244, 'Кокосовые острова', 'Cocos array(Keeling) Islands', 'CC'),
array(245, 'Западная Сахара', 'Western Sahara', 'EH'));